name: Main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: dexutar/miplus-build:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -D ENABLE_COVERAGE:BOOL=TRUE

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Run tests
      run: ctest --test-dir ${{github.workspace}}/build -C ${{env.BUILD_TYPE}}

    - name: Generate coverage report
      run: |
        lcov --rc lcov_branch_coverage=1 -c -i -d ${{github.workspace}} -o coverage.base
        lcov --rc lcov_branch_coverage=1 -d ${{github.workspace}} -c -o coverage.capture
        lcov --rc lcov_branch_coverage=1 -a coverage.base -a coverage.capture -o coverage.info
        lcov --rc lcov_branch_coverage=1 -r coverage.info '/usr/include/*' '*/test/*' -o coverage.info
      working-directory: ${{github.workspace}}

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: coverage.info