name: Main

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'containers/build.Dockerfile'
      - '.github/images.yml'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'containers/build.Dockerfile'
      - '.github/images.yml'
  
  workflow_run:
    workflows: [Images]
    types:
      - completed

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: dexutar/miplus-build:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -D ENABLE_COVERAGE:BOOL=TRUE

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Run tests
      run: ctest --test-dir ${{github.workspace}}/build -C ${{env.BUILD_TYPE}}

    - name: Generate coverage report
      run: |
        lcov -c -i -d ${{github.workspace}} -o coverage.base
        lcov -d ${{github.workspace}} -c -o coverage.capture
        lcov -a coverage.base -a coverage.capture -o coverage.info
        lcov -r coverage.info '/usr/include/*' '*/test/*' '*/mocks/*' -o coverage.info
      working-directory: ${{github.workspace}}

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: coverage.info